version: '3'
services:
    httpd:
        image: "norrlands/docker-git-httpd-sync"
        restart: "always"
        networks: ["web"]
        env_file:
          - container.env
networks:
    web:
        external: true
